### ISSUE TITLE
access domain from container

### ISSUE THREAD

**Issue by nicosmaris** [teamatldocker/jira#124]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem.
    * Checked that your issue isn't already filed.
    * Filled the form.
    * Included logs and system information.

### Description

Health check fails.

### Steps to Reproduce

1. http://jira.aug.gr/plugins/servlet/troubleshooting/view/

**Expected behavior:** All green

**Actual behavior:**

What does this check do?
Checks if JIRA is able to access itself through the gadgets feed URL to ensure that dashboard gadgets will work.

Result
JIRA is not able to access itself through the Gadget feed URL. This is necessary so that dashboard gadgets can be generated successfully. Please verify the current Base URL and if necessary, review your network configurations to resolve the problem.

**Reproduces how often:** Always

### Versions

jira 7.13 (Latest docker image blacklabelops/jira of february 4)

### Logs And Environment Information

Container logs:

```
jira_1        | 2019-02-08 21:24:58,320 HealthCheck:thread-2 ERROR      [c.a.t.j.healthcheck.support.GadgetFeedUrlHealthCheck] An error occurred when performing the Gadget feed URL healthcheck
jira_1        | org.apache.http.conn.HttpHostConnectException: Connect to jira.aug.gr:80 [jira.aug.gr/172.31.0.3] failed: Connection refused (Connection refused)
```

**Comment by blacklabelops** [comment]
You need to register your container with a network alias

Example:

~~~
jira:
    image: blacklabelops/jira
    container_name: jira
    networks:
      default:
        aliases:
          - 'jira.aug.gr'
~~~

**Comment by nicosmaris** [comment]
Unfortunately my instance at digitalocean was cryptojacked and I don't have the time to do the setup again and test it, so if you want to close this issue, feel free to do so. Thanks.
