### ISSUE TITLE
Pull atldocker/jira run into Error 

### ISSUE THREAD

**Issue by rkraemer** [teamatldocker/jira#129]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem.
    * Checked that your issue isn't already filed.
    * Filled the form.
    * Included logs and system information.

### Description

While try to start with docker-compose up -d
the following error occoured:
Pulling jira (atldocker/jira:latest)...
ERROR: pull access denied for atldocker/jira, repository does not exist or may require 'docker login'

### Steps to Reproduce

1. clone repro
2. Change docker-compose.yml from file version 3 to 2 
3. docker-compose up -d

**Expected behavior:** [What you expect to happen]

All images are downloaded and jira docker container enter running state

**Actual behavior:** [What actually happens]

pull request run into error

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
Local VM 
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8

Docker version 18.06.1-ce, build e68fc7a
docker-compose version 1.8.0

### Logs And Environment Information

Creating network "jira_jiranet" with driver "bridge"
Creating volume "jira_postgresqldata" with default driver
Creating volume "jira_jiradata" with default driver
Pulling postgresql (postgres:9.5-alpine)...
9.5-alpine: Pulling from library/postgres
bdf0201b3a05: Pull complete
365f27dc05d7: Pull complete
bf541d40dfbc: Pull complete
0bbc2b26c3af: Pull complete
2a9ccc177a0c: Pull complete
f2f00992a929: Pull complete
0ae9e5bcac44: Pull complete
19b9281e1526: Pull complete
bff1ae506973: Pull complete
Digest: sha256:92e893954c5185595d35386bf482ad571356c82ce26a61de83996ce22e507075
Status: Downloaded newer image for postgres:9.5-alpine
Pulling jira (atldocker/jira:latest)...
ERROR: pull access denied for atldocker/jira, repository does not exist or may require 'docker login'

**Comment by jhult** [comment]
This is now resolved.

Use `teamatldocker/jira`.

For additional info, see #130.
