### ISSUE TITLE
Error "manifest for teamatldocker/jira:latest not found"

### ISSUE THREAD

**Issue by aguiguy** [teamatldocker/jira#130]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem.
    * Checked that your issue isn't already filed.
    * Filled the form.
    * Included logs and system information.

### Description

Getting error message "**manifest for teamatldocker/jira:latest not found**" when attempting `docker-compose up` or `docker run`.

### Steps to Reproduce

1. git clone repo
2. docker-compose up -d

**Expected behavior:** 
Expect `jira` and `postgres` images downloaded and containers are created and enter running state.  This was last working on Apr 19, when was 'blacklabelops'.

**Actual behavior:** 
```
$ docker-compose up -d
Creating network "jira-teamatldocker_jiranet" with driver "bridge"
Creating volume "jira-teamatldocker_jiradata" with default driver
Creating volume "jira-teamatldocker_postgresqldata" with default driver
Pulling postgresql (postgres:9.5-alpine)...
9.5-alpine: Pulling from library/postgres
Pulling jira (teamatldocker/jira:)...
manifest for teamatldocker/jira:latest not found
```

**Reproduces how often:** 
100%

### Versions
current master branch

### Logs And Environment Information
Tried via Git Bash, cmd.exe, and powershell.

**Comment by LyfegenJames** [comment]
Confirmed same behaviour

**Comment by aguiguy** [comment]
Workaround for now is to modify **docker-compose.yml** to point to `image: blacklabelops/jira`.

**Comment by muhlba91** [comment]
But isn't `blacklabelops/jira` version 7.13 and the new one should be 8.1.0?
When will the newest tagged images be available on Dockerhub?

**Comment by LyfegenJames** [comment]
Confirmed that @aguiguy workaround functions fine for the moment but yes the docker images need to be tagged.

**Comment by blacklabelops** [comment]
We are still working on getting the build system back running on the new repository.

**Comment by kowalk** [comment]
@blacklabelops any news?

**Comment by kowalk** [comment]
@blacklabelops someone is here???

**Comment by blacklabelops** [comment]
Yes and no. I am preparing a workaround in the weekend.

**Comment by blacklabelops** [comment]
Okay, the build system now updates blacklabelops/jira. Please use this image until i get access to teamatldocker/jira.

**Comment by blacklabelops** [comment]
Build fixed, teamatldocker/jira now available.
