### ISSUE TITLE
8.2.3 image needed on dockerhub

### ISSUE THREAD

**Issue by rwarren** [teamatldocker/jira#133]
A recent commit bumped the version to 8.2.3 (very important due to the critical security vulnerability released this afternoon), but dockerhub does not have this image yet!

**Comment by jhult** [comment]
The test script sometimes doesn't always seem to work. I am [re-running the build now](https://circleci.com/gh/teamatldocker/jira/345) for Docker Hub.

**Comment by rwarren** [comment]
Thx, @jhult.

How do you do a standalone (non-CI) build these days? I use `./buildscripts/buildImage.sh` for confluence, but can't seem to get it right for the jira image.

**Comment by rwarren** [comment]
Weird. Failed again. Why so intermittent?

**Comment by jhult** [comment]
I haven't yet figured out why the test failure is so intermittent. However, it has now passed and Jira 8.2.3 and Service Desk 4.2.3 are available via Docker Hub.

You can see how CircleCI is configured [here](/teamatldocker/jira/blob/master/.circleci/config.yml).

You can build manually by using one of these:
1. ```./buildscripts/buildSupportedJiraImages.sh```
2. ```./buildscripts/testImage.sh latest 8220```
2. ```./buildscripts/testImage.sh core.8.2.3 8230```
