### ISSUE TITLE
upgrade to newest version - security!

### ISSUE THREAD

**Issue by domdorn** [teamatldocker/jira#134]
today, Atlassian sent out this mail: 

Hello,
--
We are writing to inform you of a critical security vulnerability that exists in Jira Server and Data Center.
Customers who have upgraded Jira Server and Data Center to versions 7.6.14, 7.13.5, 8.0.3, 8.1.2, 8.2.3 or 8.3.0 are not affected.

--
at the moment, neither 
https://hub.docker.com/r/teamatldocker/jira/tags
nor
https://hub.docker.com/r/blacklabelops/jira
offer the current version (8.2.3 or 8.3.0) of the images.

it would be great if you could publish those images.

Thx!

**Comment by jhult** [comment]
As far as I can tell, 8.3.0 is not actually released.

https://my.atlassian.com/download/feeds/current/jira-core.json
https://my.atlassian.com/download/feeds/current/jira-software.json

A [commit adding 8.2.3](/teamatldocker/jira/commit/11edb7e1a291dfe678462afff13c00b1882f4edf) was pushed earlier today. It is [building now](https://circleci.com/gh/teamatldocker/jira/345) for Docker Hub.

**Comment by domdorn** [comment]
you are a hero! 
8.3.0 is still in EAP, url would be
https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-8.3.0-EAP02-x64.bin

**Comment by jhult** [comment]
Jira 8.2.3 and Service Desk 4.2.3 are available via Docker Hub.
