### ISSUE TITLE
"Custom changes have not been carried over" after Jira upgrade

### ISSUE THREAD

**Issue by rwarren** [teamatldocker/jira#137]
With today's [announcement](https://confluence.atlassian.com/jira/jira-security-advisory-2019-09-18-976766250.html) of another critical security vulnerability, I upgraded to Jira 8.4.1.

After upgrading, Jira presented me with the following error:

![image](https://user-images.githubusercontent.com/2751728/65723548-9dd41800-e07c-11e9-890f-c66c9ae710be.png)

`bin/setenv.sh` must be getting set by the docker container automation. I need to look into it further.

The containers work fine after ignoring this message.

**Comment by jhult** [comment]
I believe this is just a warning telling you that you have modified that file. The Docker container has kept my settings just fine.

https://confluence.atlassian.com/jirasoftware/jira-software-8-3-x-release-notes-972326971.html#JiraSoftware8.3.xreleasenotes-custom

**Comment by jhult** [comment]
Whether or not this was part of 8.3.x, it is definitely part of [8.6.x](https://confluence.atlassian.com/jirasoftware/jira-software-8-6-x-release-notes-978220007.html#JiraSoftware8.6.xreleasenotes-check).

> We are ironing out upgrade hurdles for you. Now, you do not need to copy over the files you changed to keep your customizations after your upgrade. Jira detects the files you have altered in your old version and copies them to your new Jira instance. And in the meantime, you can just sit back and play around new features. See our upgrade guide for more info.

**Comment by rwarren** [comment]
FWIW, just upgraded to 8.8.1 and had the same issue again. I have not dug into it further.

**Comment by jhult** [comment]
@rwarren, I think Atlassian is always going to show this to you. I don't think this indicates an issue. Do you believe this is an issue?

**Comment by rwarren** [comment]
I do think it is an issue, if only because the message/warning is "the following warnings should be fixed".  Doing nothing as a followup doesn't seem right.  I expect it is possible to do an upgrade without having this warning (but don't know this for sure).

In addition, back when I used to manage instances manually I never got this message. I get that it may be a new thing, though.
