### ISSUE TITLE
wget TLS error to github

### ISSUE THREAD

**Issue by DaniDD** [teamatldocker/jira#141]
cant build, it shows an TLS error

**Comment by DaniDD** [comment]
apk update && apk upgrade solve this issue

**Comment by jhult** [comment]
The full error was this:

```
Connecting to github.com (140.82.112.4:443)
ssl_client: github.com: TLS connect failed
wget: error getting response: Connection reset by peer
```

The fix is adding this (before using `wget`):
```
apk add --update --no-cache --upgrade ssl_client ca-certificates-bundle
```

**Comment by rbokhorst** [comment]
I now get the following error with docker build:

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  ca-certificates-bundle (missing):
    required by: world[ca-certificates-bundle]
```

When I replace 'ca-certificates-bundle' with 'ca-certificates' it works.

**Comment by jhult** [comment]
@rbokhorst, are you building your own using the build scripts?

When I run the build locally, it is using Alpine 3.12 as the base.

It looks like `ca-certificates-bundle` was added in 3.12: https://pkgs.alpinelinux.org/packages?name=ca-*&branch=v3.12&repo=main&arch=x86_64

If you change the branch to an older version, you will not see `ca-certificates-bundle`.

`ca-certificates-bundle` is dependent on `ca-certificates`. I was able to use `ca-certificates` in the Dockerfile (even for Alpine 3.12) and it builds fine.

**Comment by rbokhorst** [comment]
Hi Jonathan, I am doing plain "docker build -t <my tag> ." using the Dockerfile in the master zip. I noticed that the adoptopenjdk/openjdk8-openj9:alpine-jre doesn't get updated once an older version already exists so I have to pull it manually. I was indeed using alpine 3.10 instead of 3.12. Is 'docker build' not the proper of building?

**Comment by jhult** [comment]
@rbokhorst,

You need to tell Docker to clear your cache. Example: `docker build --pull --no-cache -t`

See this Stackoverflow question for more details: https://stackoverflow.com/a/58115741/423351
