### ISSUE TITLE
Image needs updating to 8.22.4 (8.22.1 has a MAJOR VULNERABILITY)

### ISSUE THREAD

**Issue by rwarren** [teamatldocker/jira#152]
Jira `8.22.1` has a serious vulnerability:

https://confluence.atlassian.com/jira/jira-server-security-advisory-29nd-june-2022-1142430667.html?subid=1539287261&jobid=105629213&utm_campaign=Jira+Server+and+Data+Center-advisory-june-2022_EML-13421

The image version should be bumped to `8.22.4`.

**Comment by Firefishy** [comment]
Thank you for the report
Duplicate https://github.com/teamatldocker/jira/pull/151
